### PR TITLE
Fixed bug when user can update both price and status at the same time

### LINKED ISSUE #45: [Cooperations] A user can update both price and status at the same time
**Description:** A user can update both price and status of cooperation at the same time

**Reproducible:** always.

**Preconditions:**
The user is logged in.

**Steps to reproduce:**
1. Set price and status in body, then update a cooperation

**Actual result:**
A coopration updated

**Expected result:**
A forbidden error must appear

### PR DESCRIPTION
**Pull request by YaroslavLys**
Screenshot 2024-04-25 at 00 21 08
Screenshot 2024-04-25 at 00 21 49

### CODE REVIEW

**Review by YaroslavChuiko — APPROVED** [review]
You should add yourself to assignees in your pull requests

**Review by holus-bolus — APPROVED** [review]

**Review by khytrykv — APPROVED** [review]

**Review by voloshynvv — APPROVED** [review]

File: src/services/cooperation.js [hunk 1]
```diff
@@ -34,6 +34,10 @@ const cooperationService = {
 
     const cooperation = await Cooperation.findById(id)
 
+    if (price && status) {
```
Comment (vlad-khrychov) [inline src/services/cooperation.js]: What happen if user change price to zero value and change the status concurrently? Was it tested?

**Review by vlad-khrychov — APPROVED** [review]
